sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t laxman/docker-reactjs -f Dockerfile.dev .

script:
  - docker run -e CI=true laxman/docker-reactjs npm run test
